### PR TITLE
Fix white corners

### PR DESCRIPTION
**Pull request by jfangrad**
Gets rid of the white background that was appearing behind the LocationCreation popup.

### CODE REVIEW

**Comment by jfangrad** [comment]
[Corner rounding on the inputs is off ...](https://trello.com/c/Cx7LFhNV/160-corner-rounding-on-the-inputs-is-off)

**Comment by smaclell** [comment]
You know, I was hoping our co-ops could take this one. Oh well.

**Comment by jfangrad** [comment]
@smaclell woops my bad... should I stop fixing things that are marked `good first issue`?

**Comment by smaclell** [comment]
@jfangrad that is okay. I think we can sneak a few of those in now and then.

**Pull request merged**
